# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-09 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_location_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
