# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 15:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_quote_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='quotes',
            field=models.ManyToManyField(related_name='locations', to='app.Quote'),
        ),
    ]
