# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-10 15:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_location_quotes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='quotes',
            field=models.ManyToManyField(blank=True, related_name='locations', to='app.Quote'),
        ),
    ]
